### ISSUE TITLE
new interactive conversation to replace stats inspector

### ISSUE THREAD

**Issue by AliaElKattan** [survivalofthebestfit/survivalofthebestfit#11]
* Reference exact dataset you choose in ur response to 2nd data inspector.

**Comment by gaborcsapo** [comment]
Message #3
Msg: I’m hearing that you may be involved with this bias story. Reporters are asking for transparency! 
Interaction:

here, since the investors are getting nervous, the copy should say something like "let's run the stats to see if the algorithm is really making skewed decisions". This message sets the stage for the next inspector panel
just like with the first inspector panel, it opens up automatically when you acknowledge the investor's message. This time, we see a grid of candidates like before, but in the middle column we show some stats:
ratios of accepted/rejected applicants based evaluated by you
ratios of accepted/rejected applicants evaluated by the machine These stats are meant to reinforce the idea that the bias is present (the ratio statistic should show the yellow people are being favored).
again, you click on the message box to respond to the investor (e.g. "Indeed, the algorithm is favoring yellow people"
=== ADDITION CHECK HERE =================

in the analysis step we want to point out the difference between the data that the machine was trained on vs what we are evaluating now (to show the initial dataset was biased due to historical reasons)
as a result, showing the analysis cards in the current data inspector doesn't make too much sense, since we can only see the currently evaluated candidates and I don't think we can refer back to the people you hired out of nowhere.
I thought putting the analysis into a more "transition stage" type of conversation makes more sense.
you'd arrive in the hr laptop view, which now also has a "machine-evaluated-candidates.csv" file in the background.
in the conversation you're telling the SE:
YOU: "Hey, we need to figure out what's wrong with your algorithm, can you analyze the hires it made?"

SE: "Can you send me the decisions it has made and all the candidate information?"

[upload machine-evaluated-candidates.csv]

[returns a card of analytics with small yellow - blue people difference, but huge discrepancy between color of hired people]

YOU: "WHAT? How is this possible?" | "Why did the algorithm learn to discriminate blue people?"

SE: "Remember, how the algorithm works?

YOU: "Uhm, I sent you my decisions and the machine just mimics me?" | "I don't care, fix it!"

SE: "Yeah, if we want to fix it, we need to look at the data that you sent me, because that's what it was learning from. Can you send it again?"

[upload previously uplaoded file]

[returns analytics card with blue people underperforming previously]

YOU: "When we trained the algorithm, we didn't have many good blue candidates..." | "The data is wrong."

SE: "You should have understood your data! I just did what you asked me!"

YOU: "But you know how these things work! We should work more together..."

==========

**Comment by gaborcsapo** [comment]
yay
